apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd  # ArgoCD’s own namespace
spec:
  project: default
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    path: gitops/apps/jellyfin
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
