apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscaleProxy-appofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    path: gitops/infra/tailscaleProxy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
