apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/immich-app/immich-charts/immich
    chart: immich
    targetRevision: 0.9.3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      selfHeal: true
      prune: true