apiVersion: v2
name: immich
description: Umbrella Helm chart for Immich
version: 1.0.0
type: application
dependencies:
  - name: immich
    version: 0.9.3
    repository: https://immich-app.github.io/immich-charts
