apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    targetRevision: HEAD
    path: gitops/apps/immich
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
