apiVersion: v2
name: jellyfin
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: jellyfin
    repository: https://jellyfin.github.io/jellyfin-helm
    version: 2.3.0