apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    chart: immich
    repoURL: oci://ghcr.io/immich-app/immich-charts
    targetRevision: 0.9.3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fridge
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
