apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-project
  namespace: argocd
spec:
  description: "media server stack"
  sourceRepos:
    - "https://github.com/calbertan/kitchen-sink.git"
  destinations:
    - namespace: jellyfin
      server: https://kubernetes.default.svc
    - namespace: jellyseerr
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
