apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage-project
  namespace: argocd
spec:
  description: "storage services"
  sourceRepos:
    - 'https://github.com/calbertan/kitchen-sink.git'
  destinations:
    - namespace: immich
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
