apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage-project
  namespace: argocd
spec:
  description: "storage services"
  destinations:
  - namespace: immich
    server: https://kubernetes.default.svc
