server:
  service:
    type: ClusterIP
  # ingress:
  #   enabled: true
  #   ingressClassName: traefik
  #   annotations:
  #     kubernetes.io/ingress.class: traefik
  #   hosts:
  #     - argocd.kitchensink
  #   paths:
  #     - /
  #   pathType: Prefix

server:
  service:
    type: NodePort
    nodePort: 30080