server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - argocd.kitchensink
    paths:
      - /
    pathType: Prefix
  service:
    type: ClusterIP

server:
  service:
    type: NodePort
    nodePort: 30080