apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: apps
    repoURL: https://github.com/calbertan/kitchen-sink.git
    targetRevision: HEAD
    directory:
      recurse: true
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true
