apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_REPO/kitchen-sink.git
    path: gitops/apps/jellyseerr
    targetRevision: HEAD
    chart: jellyseerr
    repoURL: oci://ghcr.io/fallenbagel/jellyseerr/jellyseerr-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
