apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-proxy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-proxy
  template:
    metadata:
      labels:
        app: argocd-proxy
    spec:
      containers:
        - name: tailscale
          image: tailscale/tailscale:stable
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
            privileged: true
          args: ["tailscaled", "--state=/tmp/tailscaled.state"]
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: tailscale-state
              mountPath: /tmp

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d

      initContainers:
        - name: tailscale-init
          image: tailscale/tailscale:stable
          command: ["tailscale", "up", "--authkey=${TAILSCALE_AUTH_KEY}", "--hostname=argocd-proxy", "--accept-routes"]
          env:
            - name: TAILSCALE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: tailscale-state
              mountPath: /tmp

      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: tailscale-state
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: argocd-nginx-config
