apiVersion: v2
name: cloudflared
description: A Helm chart for Cloudflare Tunnel
type: application
version: 1.0.0
appVersion: "2025.10.0"

dependencies:
  - name: cloudflared
    repository: https://community-charts.github.io/helm-charts
    version: 2.2.2
