apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: test-argo-Application
  namespace: argocd
spec:
  project: test-project
  
  source:
    repoURL: https://github.com/calbertan/kitchen-sink
    targetRevision: HEAD
    path: apps
  
  destination: 
    # internal service for api server, can do this because its an internal server
    server: https://kubernetes.default.svc  
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
