# App of apps
apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calbertan/kitchen-sink
    targetRevision: HEAD
    path: .
  
  destination: 
    # internal service for api server, can do this because its an internal server
    server: https://kubernetes.default.svc  
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
