apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-nginx-config
  namespace: infra
data:
  default.conf: |
    server {
        listen 8443 ssl;
        ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

        location / {
            proxy_pass https://argocd-server.argocd.svc.cluster.local:443;
            proxy_ssl_verify off;
        }
    }
