apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-proxy-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    targetRevision: HEAD
    path: gitops/infra/argocd/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
