apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: storage-project
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    targetRevision: HEAD
    path: gitops/apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  