apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: media-project
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    targetRevision: HEAD
    path: gitops/apps/jellyseerr
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyseerr
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  