apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: networking-project
  source:
    repoURL: https://github.com/calbertan/kitchen-sink.git
    targetRevision: HEAD
    path: gitops/apps/tailscale
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale