apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd    # where ArgoCD is running
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.9.2     # pin the chart version you want
    # helm:
    #   values: |
    #     server:
    #       ingress:
    #         enabled: true
    #         ingressClassName: nginx
    #         hosts:
    #           - argocd.example.tailnet
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
