apiVersion: v2
name: argocd
description: Umbrella Helm chart for Argocd
version: 1.0.0
type: application
dependencies:
  - name: argo-cd
    version: 6.9.2 
    repository: https://argoproj.github.io/argo-helm
