apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
spec:
  defaultBackend:
    service:
      name: argocd-server
      port:
        number: 443

  ## if multiiple ingress types, determine which method we are using
  ingressClassName: tailscale
  tls:
    - hosts:
      - argocd